sudo: required
dist: trusty
language: node_js
node_js: 7
cache:
  yarn: true
  directories:
    - node_modules

install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - yarn install

script:
  - yarn run lint
  - yarn test
  - yarn run build
