export const REMEMBER_ARTICLE_VIEW_STATE = 'REMEMBER_ARTICLE_VIEW_STATE';
export const UPDATE_ARTICLE_VIEW_STATE = 'UPDATE_ARTICLE_VIEW_STATE';
export const FETCH_ARTICLE_VIEW_STATE = 'FETCH_ARTICLE_VIEW_STATE';
